### ISSUE TITLE
Audio Context expects 3 args

### ISSUE THREAD

**Issue by daviddias** [websound/RemotePerformer#7]
It seems that the API has changed, the values we currently passing as args are way different of what API describes

``` JavaScript
App.audioBuffer = App.audioContext.createBuffer(event.target.response, false)
```

https://github.com/websound/RemotePerformer/blob/master/src/public/js/app.js#L67

https://developer.mozilla.org/en-US/docs/Web/API/AudioContext/createBuffer

**Comment by obensource** [comment]
This Issue is up for review and will be addressed or closed soon.
